#!/usr/bin/env sh

resource=$2
outfile=$1

for i in $SECTIONS; do
  chapter=`basename $i .txt`

  echo "$chapter"

  curl -o tmp/$chapter.html --remote-name $resource/$chapter.html
done

zip -r $outfile tmp/*.html


