#!/usr/bin/env sh

outfile=$1

resource=$2

mkdir -p tmp/$DOMAIN/$COURSE

for i in $SECTIONS; do
  chapter=`basename $i .txt`

  curl -o tmp/$DOMAIN/$COURSE/$chapter.html --remote-name $resource/$chapter.html
done

zip -r $outfile tmp/$DOMAIN/$COURSE/*.html


