name: backlog
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    - name: build yaaghs @ 1593566360
    - uses: actions/checkout@v2
      with:
        repository: arthur-stace/yaaghs
