name: data
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    steps:
    - name: build yaaghs @ 1593557779
    - runs-on: ubuntu-latest
    - uses: actions/checkout@v2
      with:
        repository: arthur-stace/yaaghs
      env:
        PROJECT: arthur-stace/rails
      run: docker build yaaghs --tag yaaghs:1593557779
