name: data
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    steps:
    - uses: actions/checkout@master
      with: arthur-stace/yaaghs
    - name: build yaaghs @ 1593557152
      env:
        PROJECT: arthur-stace/rails
      run: docker build yaaghs --tag yaaghs:1593557152
