name: build radicale
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build radicale
      run: docker build radicale --file radicale/Dockerfile --tag radicale:$(date
        +%s)
